settings:
  parallelExecution: false
  retryOnFailure: true

tasks:
  - id: readAudience
    type: read_write_file
    config:
      operation: read
      filePath: workflows/data/target_audience.txt
      variableName: "TARGET_AUDIENCE" # Assign this to the {{TARGET_AUDIENCE}} field in the prompt
      retryOnFail: false
      continueOnFail: false

  - id: readProblem
    type: read_write_file
    config:
      operation: read
      filePath: workflows/data/target_audience_problem.txt
      variableName: "PROBLEM" # Assign this to the {{PROBLEM}} field in the prompt
      retryOnFail: false
      continueOnFail: false

  - id: identifyPersonas
    type: ai_agent
    dependencies:
      - readAudience
      - readProblem
    config:
      llmConfig:
        model: "gpt-4o"
        temperature: 0.0
        maxTokens: 2048
        provider: openai
      promptId: business_identify_personas # Prompt requires {{TARGET_AUDIENCE}} and {{PROBLEM}} to work
      retryOnFail: false
      continueOnFail: false

  - id: bestYearEver
    type: ai_agent
    dependencies:
      - identifyPersonas
    config:
      llmConfig:
        model: "gpt-4o"
        temperature: 0.0
        maxTokens: 2048
        provider: openai
      promptId: business_persona_best_year_ever
      retryOnFail: false
      continueOnFail: false

  - id: createPitchNode
    type: ai_agent
    dependencies:
      - identifyPersonas
      - bestYearEver
    config:
      llmConfig:
        provider: openai
        model: "gpt-4o"
        temperature: 0.0
        maxTokens: 2048
      promptId: business_create_pitch
      retryOnFail: false
      continueOnFail: false

  - id: writeOutput
    type: read_write_file
    dependencies:
      - createPitchNode
    config:
      operation: write
      filePath: "workflows/data/output.txt"
