settings:
  parallelExecution: false
  retryOnFailure: true

tasks:
  - id: readInput
    type: file_read
    config:
      filePath: "input/input.txt"

  - id: identifyPersonas
    type: ai_request
    dependencies:
      - readInputNode
    config:
      llmConfig:
        model: "text-davinci-003"
        temperature: 0.7
        maxTokens: 150
        provider: openai
      promptId: business_identify_personas

  - id: bestYearEver
    type: ai_request
    dependencies:
      - identifyPersonasNode
    config:
      llmConfig:
        model: "text-davinci-003"
        temperature: 0.7
        maxTokens: 150
        provider: openai
      promptId: business_persona_best_year_ever

  - id: createPitchNode
    type: ai_request
    dependencies:
      - bestYearEverNode
    config:
      llmConfig:
        provider: openai
        model: "text-davinci-003"
        temperature: 0.7
        maxTokens: 150
      promptId: business_create_pitch

  - id: writeOutput
    type: write_file
    dependencies:
      - createPitchNode
    config:
      filePath: "output/output.txt"
