settings:
  parallelExecution: false
  retryOnFailure: true

tasks:
  - id: readInput
    type: read_write_file
    config:
      operation: read
      filePath: "input.txt"

  - id: identifyPersonas
    type: ai_agent
    dependencies:
      - readInput
    config:
      llmConfig:
        model: "text-davinci-003"
        temperature: 0.7
        maxTokens: 150
        provider: openai
      promptId: business_identify_personas

  - id: bestYearEver
    type: ai_agent
    dependencies:
      - identifyPersonas
    config:
      llmConfig:
        model: "text-davinci-003"
        temperature: 0.7
        maxTokens: 150
        provider: openai
      promptId: business_persona_best_year_ever

  - id: createPitchNode
    type: ai_agent
    dependencies:
      - identifyPersonas
      - bestYearEver
    config:
      llmConfig:
        provider: openai
        model: "text-davinci-003"
        temperature: 0.7
        maxTokens: 150
      promptId: business_create_pitch

  - id: writeOutput
    type: read_write_file
    dependencies:
      - createPitchNode
    config:
      operation: write
      filePath: "output.txt"
